ProFIT/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Displays the attendee&apos;s email</description>
        <inlineHelpText>Enter the attendee&apos;s email</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFIT/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the location of the event</description>
        <inlineHelpText>Choose the location of the event</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Displays the name of the event</description>
        <inlineHelpText>Enter the name of the event</inlineHelpText>
        <label>Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the name of the event organizer</description>
        <inlineHelpText>Choose the event organizer</inlineHelpText>
        <label>Organizer</label>
        <referenceTo>Event_Organizer__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Displays the event&apos;s starting date/time</description>
        <inlineHelpText>Enter the event&apos;s starting date/time</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFIT/objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Displays the name of the attendee of the event</description>
        <inlineHelpText>Choose the name of the attendee of the event</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Events-Attendees</relationshipLabel>
        <relationshipName>Events_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Displays the name of the event</description>
        <inlineHelpText>Choose the name of the event</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Events-Attendees</relationshipLabel>
        <relationshipName>Events_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event-Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFIT/objects/Event_Organizer__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Displays the organizer&apos;s email</description>
        <inlineHelpText>Enter the organizer&apos;s email</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFIT/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>Displays the city location</description>
        <inlineHelpText>Enter the name of the city</inlineHelpText>
        <label>City</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Displays the country location</description>
        <inlineHelpText>Choose the location of country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Deps</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Displays the the postal code of the location</description>
        <inlineHelpText>Enter the postal code of the location</inlineHelpText>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Displays the state location</description>
        <inlineHelpText>Enter the name of the state</inlineHelpText>
        <label>State</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Displays the name of the street.</description>
        <inlineHelpText>Enter the name of the street</inlineHelpText>
        <label>Street</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFIT/classes/EventAttendeeClass.cls
public with sharing class EventAttendeeClass {
    //Sends an email notification to the Attendee when a new Event_Attendee record is created.
    public static void EventAttendeeSendEmail(List<Event_Attendee__c> newAttendeeList) {
        try {            
            for(Event_Attendee__c esRecord : newAttendeeList){
                //Obtains, and assigns the ID of each object from the Event_Attendee object
                Id attendeeId = (Id)esRecord.get('Attendee__c');
                Id eventId = (Id)esRecord.get('Event__c');
                
                //Obtains the following fields from each object, and stores it into a Map.
                Map<Id, Attendee__c> attendeeMap = new Map<Id, Attendee__c>([SELECT ID, Name, Email__c FROM Attendee__c WHERE Id =: attendeeId]);
                Map<Id, Event__c > eventMap = new Map<Id, Event__c> ([Select Id, Name__c, Start_Date_Time__c, Organizer__c , Organizer__r.Name, Location__c , Location__r.Name, Location__r.City__c, Location__r.State__c, Location__r.Country__c, Location__r.Postal_Code__c, Location__r.Street__c FROM Event__c  where ID =: eventId]);

                //Obtains the Id from the Map, and stores it into each custom object.
                Attendee__c attendeeRec = attendeeMap.get(esRecord.Attendee__c);
                Event__c eventRec = eventMap.get(esRecord.Event__c);
                // System.debug(attendeeRec);
                
                //Initializes a single email message
                Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                
                //Sets the subject line for the email
                message.setSubject('Pass for the ' + eventRec.Name__c);
                System.debug('Pass for the ' + eventRec.Name__c);
                
                //Initalizes a list of string, and adds the email account of the attendee to list. Once there is an email in the list, the recipient of the email will be the attendee.
                List<String> emailAdd = new List<String>();
                emailAdd.add(attendeeRec.Email__c);
                System.debug(attendeeRec.Email__c);
                message.setToAddresses(emailAdd);

                //Sets the name of the sender to the Event Organizer.
                message.setSenderDisplayName(eventRec.Organizer__r.Name);
                
                //Sets the message of the email itself.
                String linkForLocation = '<a href="https://www.google.com/maps/place'+eventRec.Location__r.Street__c+' '+eventRec.Location__r.City__c+' '+eventRec.Location__r.State__c+' '+eventRec.Location__r.Country__c+' '+eventRec.Location__r.Postal_Code__c+'"'+'target="_blank">Here</a>';
                
                String body = 'Dear '+attendeeRec.Name+',<br/>Thank you for registering for <strong>'+eventRec.Name__c+'</strong> which will be Organized on <strong>'+eventRec.Start_Date_Time__c+'</strong> & will be held in <strong>'+eventRec.Location__r.Name+'</strong>. We are excited to have you, see you in the event.<br/><br/>Find the Google Map Location for the Event Here.<br/>'+linkForLocation+'<br/>Thanks,<br/><strong>'+eventRec.Organizer__r.Name+'</strong>';
                
                message.setHtmlBody(body);
                
                //Stores the List of SingleEmailMessage message into an array, then it sends an email to the attendee.
                Messaging.SingleEmailMessage[] messages = 
                new List<Messaging.SingleEmailMessage> {message};
                Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);

                //Checks if the first index of results array is a success.
                if (results[0].success) {
                    System.debug('The email was sent successfully.');
                } else {
                    System.debug('The email failed to send: '
                    + results[0].errors[0].message);
                }            
                
            }
        } catch (Exception ex) {
            System.debug('The following exception has occurred: ' + ex.getMessage());
        }
    }
}