ProFIT/objects/Attendee__c.object
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFIT/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>Displays the event&apos;s end date/time</description>
        <inlineHelpText>Enter the event&apos;s end date/time</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <description>Displays the type of the event</description>
        <inlineHelpText>Choose the type of the event</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Displays if the event is live or not</description>
        <inlineHelpText>Check if the event is live</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the location of the event</description>
        <inlineHelpText>Choose the location of the event</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Displays the maximum capacity for the event</description>
        <inlineHelpText>Enter the maximum capacity for the event</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Displays the name of the event</description>
        <inlineHelpText>Enter the name of the event</inlineHelpText>
        <label>Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the name of the event organizer</description>
        <inlineHelpText>Choose the event organizer</inlineHelpText>
        <label>Organizer</label>
        <referenceTo>Event_Organizer__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remaining_Seats__c</fullName>
        <description>Displays the remaining number of seats for the event</description>
        <formula>Max_Seats__c -  People_Attending__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the remaining number of seats for the event</inlineHelpText>
        <label>Remaining Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Displays the event&apos;s starting date/time</description>
        <inlineHelpText>Enter the event&apos;s starting date/time</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFIT/objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Displays the name of the attendee of the event</description>
        <inlineHelpText>Choose the name of the attendee of the event</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Events-Attendees</relationshipLabel>
        <relationshipName>Events_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Displays the name of the event</description>
        <inlineHelpText>Choose the name of the event</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Events-Attendees</relationshipLabel>
        <relationshipName>Events_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event-Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFIT/objects/Event_Organizer__c.object
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFIT/objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFIT/classes/AttendeeEventsService.cls
public with sharing class AttendeeEventsService {
    @AuraEnabled(cacheable = true)
    //Returns a list of Event_Attendee where Attendee is equal to record ID, Start Date is in the future, and Live is checked.
    public static List<Event_Attendee__c> upcomingEvents(String attendeeId) {
      List<Event_Attendee__c> eventLists = [
        SELECT
          Id,
          Name,
          Event__c,
          Event__r.Name,
          Event__r.Event_Type__c,
          Event__r.Location__c,
          Event__r.Location__r.Name,
          Event__r.Organizer__c,
          Event__r.Organizer__r.Name,
          Event__r.Name__c,
          Event__r.Start_Date_Time__c,
          Event__r.End_Date_Time__c,
          Event__r.Max_Seats__c,
          Event__r.Remaining_Seats__c
        FROM Event_Attendee__c
        WHERE
          Attendee__c = :attendeeId
          AND Event__r.Start_Date_Time__c >= today
          AND Event__r.Live__c = true
      ];
      return eventLists;
    }
  
    @AuraEnabled(cacheable = true)
    //Returns a list of Event_Attendee where Attendee is equal to record ID, and Start Date is in the past.
    public static List<Event_Attendee__c> pastEvents(String attendeeId) {
      List<Event_Attendee__c> eventLists = [
        SELECT
          Id,
          Name,
          Event__c,
          Event__r.Name,
          Event__r.Event_Type__c,
          Event__r.Location__c,
          Event__r.Location__r.Name,
          Event__r.Organizer__c,
          Event__r.Organizer__r.Name,
          Event__r.Name__c,
          Event__r.Start_Date_Time__c,
          Event__r.End_Date_Time__c,
          Event__r.Max_Seats__c,
          Event__r.Remaining_Seats__c
        FROM Event_Attendee__c
        WHERE Attendee__c = :attendeeId AND Event__r.Start_Date_Time__c < today
      ];
      return eventLists;
    }
  }