ProFIT/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the address of the attendee&apos;s company</description>
        <inlineHelpText>Choose the address of the attendee&apos;s company</inlineHelpText>
        <label>Address</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Displays the attendee&apos;s current company</description>
        <inlineHelpText>Enter the attendee&apos;s current company</inlineHelpText>
        <label>Company Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Displays the attendee&apos;s email</description>
        <inlineHelpText>Enter the attendee&apos;s email</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Displays the attendee&apos;s phone number</description>
        <inlineHelpText>Enter the attendee&apos;s phone number</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFIT/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>Displays the event&apos;s end date/time</description>
        <inlineHelpText>Enter the event&apos;s end date/time</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the location of the event</description>
        <inlineHelpText>Choose the location of the event</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Displays the maximum capacity for the event</description>
        <inlineHelpText>Enter the maximum capacity for the event</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Displays the name of the event</description>
        <inlineHelpText>Enter the name of the event</inlineHelpText>
        <label>Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remaining_Seats__c</fullName>
        <description>Displays the remaining number of seats for the event</description>
        <formula>Max_Seats__c -  People_Attending__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Displays the remaining number of seats for the event</inlineHelpText>
        <label>Remaining Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Displays the event&apos;s starting date/time</description>
        <inlineHelpText>Enter the event&apos;s starting date/time</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFIT/objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Displays the name of the attendee of the event</description>
        <inlineHelpText>Choose the name of the attendee of the event</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Events-Attendees</relationshipLabel>
        <relationshipName>Events_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Displays the name of the event</description>
        <inlineHelpText>Choose the name of the event</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Events-Attendees</relationshipLabel>
        <relationshipName>Events_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event-Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFIT/objects/Event_Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <description>Displays the name of the event</description>
        <inlineHelpText>Choose the name of the event</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Events-Speakers</relationshipLabel>
        <relationshipName>Events_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>Displays the name of the speaker of the event</description>
        <inlineHelpText>Choose the name of the speaker of the event</inlineHelpText>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Events-Speakers</relationshipLabel>
        <relationshipName>Events_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Event-Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFIT/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <description>Displays the city location</description>
        <inlineHelpText>Enter the name of the city</inlineHelpText>
        <label>City</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Displays the country location</description>
        <inlineHelpText>Choose the location of country</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua &amp; Deps</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Landmark__c</fullName>
        <description>Shows the landmark for the location</description>
        <inlineHelpText>Enter the landmark for the location</inlineHelpText>
        <label>Landmark</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Displays the the postal code of the location</description>
        <inlineHelpText>Enter the postal code of the location</inlineHelpText>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Displays the state location</description>
        <inlineHelpText>Enter the name of the state</inlineHelpText>
        <label>State</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Displays the name of the street.</description>
        <inlineHelpText>Enter the name of the street</inlineHelpText>
        <label>Street</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFIT/objects/Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <description>Displays the speaker&apos;s current company</description>
        <inlineHelpText>Enter the speaker&apos;s current company</inlineHelpText>
        <label>Company</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Displays the speaker&apos;s email</description>
        <inlineHelpText>Enter the speaker&apos;s email</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Displays the speaker&apos;s phone number</description>
        <inlineHelpText>Enter the speaker&apos;s phone number</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFIT/classes/EventDetailsController.cls
public with sharing class EventDetailsController {
    @AuraEnabled(cacheable = true)
    public static List<Event_Speaker__c> getSpeakers(String eventId){
        try {
            List<Event_Speaker__c> speakerLst = [Select Id, Name, Speaker__r.Name, Speaker__r.Email__c, Speaker__r.Phone__c, Speaker__r.Company__c from Event_Speaker__c where Event__c =: eventId];

            return speakerLst;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled(cacheable = true) 
    public static Event__c getLocationDetails(String eventId){
        try {
            Event__c eventRec = [Select Id, Name__c, Location__r.Name, Location__c, Location__r.City__c, Location__r.Country__c, Location__r.Landmark__c, Location__r.Postal_Code__c, Location__r.State__c, Location__r.Street__c from Event__c where Id =: eventId];
            
            return eventRec;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled(cacheable = true) 
    public static List<Event_Attendee__c> getAttendees(String eventId){
        try {
            List<Event_Attendee__c> evtAttLst = [Select Id, Name, Attendee__r.Name, Attendee__r.Email__c, Attendee__r.Address__c, Attendee__r.Address__r.Name, Attendee__r.Company_Name__c, Attendee__r.Phone__c, Event__r.Start_Date_Time__c, Event__r.End_Date_Time__c, Event__r.Max_Seats__c, Event__r.Remaining_Seats__c from Event_Attendee__c where Event__c =: eventId];

            return evtAttLst;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }  
}