ProFIT/objects/Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Displays the attendee&apos;s email</description>
        <inlineHelpText>Enter the attendee&apos;s email</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Displays the attendee&apos;s phone number</description>
        <inlineHelpText>Enter the attendee&apos;s phone number</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFIT/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>Displays the event&apos;s end date/time</description>
        <inlineHelpText>Enter the event&apos;s end date/time</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Displays if the event is live or not</description>
        <inlineHelpText>Check if the event is live</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Displays the maximum capacity for the event</description>
        <inlineHelpText>Enter the maximum capacity for the event</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Displays the name of the event</description>
        <inlineHelpText>Enter the name of the event</inlineHelpText>
        <label>Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the name of the event organizer</description>
        <inlineHelpText>Choose the event organizer</inlineHelpText>
        <label>Organizer</label>
        <referenceTo>Event_Organizer__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Displays the event&apos;s starting date/time</description>
        <inlineHelpText>Enter the event&apos;s starting date/time</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFIT/objects/Event_Attendee__c.object
<CustomObject>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Displays the name of the attendee of the event</description>
        <inlineHelpText>Choose the name of the attendee of the event</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Events-Attendees</relationshipLabel>
        <relationshipName>Events_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Displays the name of the event</description>
        <inlineHelpText>Choose the name of the event</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Events-Attendees</relationshipLabel>
        <relationshipName>Events_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Attendee</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Event-Attendee Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events-Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFIT/objects/Event_Organizer__c.object
<CustomObject>
    <fields>
        <fullName>Alternative_Email__c</fullName>
        <description>Displays the organizer&apos;s alternate email</description>
        <inlineHelpText>Enter the organizer&apos;s alternate email</inlineHelpText>
        <label>Alternative Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Alternative_Phone__c</fullName>
        <description>Displays the organizer&apos;s alternate phone number</description>
        <inlineHelpText>Enter the organizer&apos;s alternate phone number</inlineHelpText>
        <label>Alternative Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Displays the organizer&apos;s email</description>
        <inlineHelpText>Enter the organizer&apos;s email</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Displays the organizer&apos;s phone number</description>
        <inlineHelpText>Enter the organizer&apos;s phone number</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFIT/classes/EventAttendeeClass_Test.cls
@IsTest
private class EventAttendeeClass_Test {
    @IsTest
    static void updateValues() {
        Test.startTest();
        
        Event_Organizer__c evtOrgTest = new Event_Organizer__c();
        evtOrgTest.Name = 'Sample Event Organizer';
        evtOrgTest.Phone__c = '112233445566';
        evtOrgTest.Email__c = 'sampleeventorganizer@mail.com';
        evtOrgTest.Alternative_Phone__c = '112233445566';
        evtOrgTest.Alternative_Email__c = 'sampleeventorganizer@mail.com';
        Database.insert(evtOrgTest);

        Event__c eventTest = new Event__c();
        eventTest.Name__c = 'Sample Event';
        eventTest.Organizer__c = evtOrgTest.Id;
        eventTest.Max_Seats__c = 100;
        eventTest.Live__c = true;
        eventTest.Start_Date_Time__c = System.now();
        eventTest.End_Date_Time__c = System.now().addDays(1);
        Database.insert(eventTest);

        Attendee__c attendeeTest = new Attendee__c();
        attendeeTest.Name = 'Sample Attendee';
        attendeeTest.Email__c = 'charlesjustin1998@gmail.com';
        attendeeTest.Phone__c = '65544332211';
        Database.insert(attendeeTest);

        Event_Attendee__c evtAttTest = new Event_Attendee__c();
        evtAttTest.Event__c = eventTest.Id;
        evtAttTest.Attendee__c = attendeeTest.Id;
        Database.insert(evtAttTest);

        try{
            integer i = 10/0;
        }
        catch(Exception ex){
            
        }
        Test.stopTest();
        

    }
}