ProFIT/objects/Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Log_Date_Time__c</fullName>
        <description>Stores the Date&amp;Time details when the Error occured</description>
        <inlineHelpText>Stores the Date&amp;Time details when the Error occured</inlineHelpText>
        <label>Log Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Log_Details__c</fullName>
        <description>Stores the Complete Stack Track about the Error</description>
        <inlineHelpText>Stores the Complete Stack Track about the Error</inlineHelpText>
        <label>Log Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Process_Name__c</fullName>
        <description>States the name of either apex class or apex trigger</description>
        <inlineHelpText>States the name of either apex class or apex trigger</inlineHelpText>
        <label>Process Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ER-{0000}</displayFormat>
        <label>Log#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProFIT/classes/ErrorLogGenerator_Test.cls
@isTest
//Test if there is 'Test Error Name' value in the Error_Log__c ErrorLogGenerator().
public with sharing class ErrorLogGenerator_Test {
    @IsTest
    static void testError(){
        
        Test.startTest();
        Date logDate = date.newInstance(2021, 6, 21);
        String logDetails = 'Error Test';
        String name = 'Test Error Name';
        ErrorLogGenerator.ErrorLogGenerator(logDate, logDetails, name);
        
        Test.stopTest();
        try{
            Error_Log__c eLog = [Select Id, Log_Date_Time__c,Log_Details__c,Process_Name__c from Error_Log__c];
            System.assertEquals('Test Error Name', eLog.Process_Name__c);
        }
        catch(Exception ex){
            System.debug(ex);
        }
    }
}