ProFIT/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>Displays the event&apos;s end date/time</description>
        <inlineHelpText>Enter the event&apos;s end date/time</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Displays if the event is live or not</description>
        <inlineHelpText>Check if the event is live</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Displays the name of the event</description>
        <inlineHelpText>Enter the name of the event</inlineHelpText>
        <label>Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Displays the event&apos;s starting date/time</description>
        <inlineHelpText>Enter the event&apos;s starting date/time</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFIT/objects/Event_Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <description>Displays the name of the event</description>
        <inlineHelpText>Choose the name of the event</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Events-Speakers</relationshipLabel>
        <relationshipName>Events_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>Displays the name of the speaker of the event</description>
        <inlineHelpText>Choose the name of the speaker of the event</inlineHelpText>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Events-Speakers</relationshipLabel>
        <relationshipName>Events_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event-Speaker</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Event-Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProFIT/objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProFIT/classes/EventSpeakerValidation_Test.cls
@IsTest
private class EventSpeakerValidation_Test {

    static Id createTestRecordID(){
        Event__c evt = new Event__c();
        evt.Name__c = 'Test Event';
        evt.Live__c = true;
        evt.Start_Date_Time__c = datetime.newInstance(2021, 6, 21, 19, 30, 0);
        evt.End_Date_Time__c = datetime.newInstance(2021, 6, 22, 20, 30, 0);
        Database.insert(evt);
        return evt.Id;
    }

        @IsTest
      Static void checkEventEspeaker(){
        Test.startTest();

        try{
        Event_Speaker__c eS = new Event_Speaker__c();
        //Field Names
        //Create a new data to object
        eS.Event__c = createTestRecordID();
        eS.Speaker__c = 'a080l00000BCp3bAAD';
        
        Database.insert(eS);
        

        Event_Speaker__c retrievedES = [Select Id from Event_Speaker__c where Name =: eS.Speaker__c];

        System.assertEquals('a080l00000BCp3bAAD',retrievedES.Speaker__c);
        }
        catch (Exception ex){
            Test.stopTest();
        }
      }
}