ProFIT/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>Displays the event&apos;s end date/time</description>
        <inlineHelpText>Enter the event&apos;s end date/time</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Displays if the event is live or not</description>
        <inlineHelpText>Check if the event is live</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Displays the maximum capacity for the event</description>
        <inlineHelpText>Enter the maximum capacity for the event</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Displays the name of the event</description>
        <inlineHelpText>Enter the name of the event</inlineHelpText>
        <label>Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Displays the event&apos;s starting date/time</description>
        <inlineHelpText>Enter the event&apos;s starting date/time</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Displays the status of the event</description>
        <inlineHelpText>Choose the status of the event</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Postponed</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProFIT/classes/DeleteEventBatch_Test.cls
@IsTest
public with sharing class DeleteEventBatch_Test {
    @IsTest
    //Test if there 200 records were updated prior to their Status.
    static void DeleteEventBatch_Test() {
        List<Event__c> eventTestLst = new List<Event__c>();
        Integer count = 1;
        while(count <= 200){
            Event__c eventTest = new Event__c();
            eventTest.Name__c = 'Sample Event ' + count;
            eventTest.Status__c = 'Created';
            eventTest.Max_Seats__c = 50;
            eventTest.Live__c = false;
            eventTest.Start_Date_Time__c = Datetime.newInstance(2020, 12, 24, 12, 0, 0);
            eventTest.End_Date_Time__c = Datetime.newInstance(2020, 12, 25, 12, 0, 0);
            eventTestLst.add(eventTest);
            count++;
        }
        Database.insert(eventTestLst);
        System.debug(eventTestLst);
        Test.startTest();
        
        DeleteEventBatch delEvtBat = new DeleteEventBatch();
        Database.executeBatch(delEvtBat);

        System.assertEquals(200, [Select count() from Event__c]);

        Test.stopTest();       
    }
}